### ISSUE TITLE
8/10 발견된 오류

### ISSUE THREAD

**Issue by marunemo** [marunemo/Hanchelin_Guide#25]
1. RestHome.js 에서 CircleIcon이 선언되거나 import 되지 않아 발생하는 오류
2. RestHome.js 에서 Navigator의 header의 글자 위치가 망가지는 오류

**Comment by seokmin01** [comment]
CircleIcon과 AddIcon을 native-base section에 import함으로 1번째 오류를 해결할 수 있었습니다.

**Comment by seokmin01** [comment]
2번째 오류는 Bottom Tab Navigator와 관련된 오류로 보입니다. 해결하지 못했습니다.

**Comment by seokmin01** [comment]
`<Stack.Screen name="식당 리스트" component={Home}
                options={{
                    headerLeft: () => (
                        <NativeBaseProvider>
                            <TouchableOpacity style={{ marginLeft: 10, marginTop: 10, size: 10 }}
                                onPress={() => navigation.navigate('프로필')}>
                                    <HamburgerIcon />
                            </TouchableOpacity>
                        </NativeBaseProvider>
                    ),
                    headerRight: () => (
                        <NativeBaseProvider>
                            <TouchableOpacity style={{ marginRight: 10, marginTop: 10, size: 10 }}
                                onPress={() => navigation.navigate('채팅')}>
                                    <CircleIcon />
                            </TouchableOpacity>
                        </NativeBaseProvider>
                    )
                }} />`
TouchableOpacity의 style에서 margin으로 인한 오류입니다. 코드 수정이 필요합니다.

**Comment by marunemo** [comment]
> 2번째 오류는 Bottom Tab Navigator와 관련된 오류로 보입니다. 해결하지 못했습니다.

Bottom Tab Navigator는 RestHome.js와 DeliverScreen에서의 Navigator Header 중복 사용을 막기 위해 헤더를 제거했기 때문에 아마 RestHome.js의 navigator에서 해결해야 할 것 같습니다.

**Comment by seokmin01** [comment]
RestHome.js의 상단탭 코드를 수정했습니다! NativeBaseProvider를 상단 탭에 적용함으로써 발생한 오류였습니다.
